# Generated by Django 4.0.2 on 2022-03-03 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_students_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staff',
            options={'permissions': (('Staff', 'Staff'),)},
        ),
    ]
